### ISSUE TITLE
seguimiento y control

### ISSUE THREAD

**Issue by carlos-chrs** [SistemasTecTlaxiaco/actividad-9-practica-de-seguimiento-y-control-de-proyecto-entrevista-gestion-de-proyectos#1]
[Practica de Seguimiento Y Control Horizon.pdf](https://github.com/SistemasTecTlaxiaco/actividad-9-practica-de-seguimiento-y-control-de-proyecto-entrevista-gestion-de-proyectos/files/10189919/Practica.de.Seguimiento.Y.Control.Horizon.pdf)

**Comment by Ferch0419** [comment]
Buen trabajo: 50/50.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
